# Generated by Django 5.1.6 on 2025-04-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_doctorprofile_user_alter_patientprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
