# Generated by Django 5.1.6 on 2025-04-03 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0001_initial'),
        ('users', '0004_alter_doctorprofile_license_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_notes', models.TextField(blank=True, null=True)),
                ('condition', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctordiagnosis', to='users.doctorprofile')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientdiagnosis', to='users.patientprofile')),
            ],
        ),
    ]
