# Generated by Django 5.1.6 on 2025-04-04 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0002_diagnosis'),
        ('users', '0005_alter_doctorprofile_user_alter_patientprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_diagnosis', to='users.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_diagnosis', to='users.patientprofile'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='users.patientprofile'),
        ),
        migrations.CreateModel(
            name='LabResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xray', models.FileField(blank=True, null=True, upload_to='xrays/')),
                ('vitalsigns', models.JSONField(blank=True, null=True)),
                ('blood_test_results', models.JSONField(blank=True, null=True)),
                ('urinalysis_results', models.JSONField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record_lab_results', to='patient_records.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_lab_results', to='users.patientprofile')),
            ],
        ),
    ]
