# Generated by Django 5.1.6 on 2025-04-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0003_alter_diagnosis_doctor_alter_diagnosis_patient_and_more'),
        ('users', '0005_alter_doctorprofile_user_alter_patientprofile_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LabResults',
            new_name='LabResult',
        ),
    ]
