# Generated by Django 5.1.6 on 2025-04-05 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0004_rename_labresults_labresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patient_records.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='patient_records.medicalrecord'),
        ),
    ]
