# Generated by Django 5.1.6 on 2025-04-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dosage_form', models.CharField(max_length=100)),
                ('strength', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('mg', 'Milligram (mg)'), ('g', 'Gram (g)'), ('ml', 'Milliliter (ml)'), ('l', 'Liter (l)'), ('%', 'Percentage (%)'), ('mcg', 'Microgram (mcg)')], max_length=10)),
            ],
        ),
    ]
