# Generated by Django 5.1.6 on 2025-04-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='unit',
            field=models.CharField(choices=[('mg', 'mg'), ('g', 'g'), ('ml', 'ml'), ('l', ' (l)'), ('%', '%'), ('mcg', 'mcg')], max_length=10),
        ),
    ]
