# Generated by Django 5.1.6 on 2025-04-05 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_alter_medication_unit'),
        ('prescriptions', '0002_alter_prescription_medical_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescriptions.prescription'),
        ),
    ]
