# Generated by Django 5.1.6 on 2025-04-05 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_medication_prescription'),
        ('prescriptions', '0003_remove_prescription_medication_prescription_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='prescriptions.prescription'),
        ),
    ]
