# Generated by Django 5.1.6 on 2025-04-04 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medications', '0002_alter_medication_unit'),
        ('patient_records', '0004_rename_labresults_labresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(help_text='E.g., Twice a day, Every 6 hours', max_length=100)),
                ('quantity', models.PositiveIntegerField(help_text='Total quantity prescribed')),
                ('duration', models.PositiveIntegerField(help_text='Duration in days')),
                ('instructions', models.TextField(blank=True, help_text='Additional instructions for the patient', null=True)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Dispensed', 'Dispensed'), ('Cancelled', 'Cancelled')], default='pending', help_text='Current status of the prescription', max_length=10)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_prescriptions', to='patient_records.medicalrecord')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_prescriptions', to='medications.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
