# Generated by Django 5.1.6 on 2025-04-05 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_alter_medication_unit'),
        ('patient_records', '0005_alter_diagnosis_medical_record_and_more'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patient_records.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_prescriptions', to='medications.medication'),
        ),
    ]
