# Generated by Django 5.1.6 on 2025-04-05 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_alter_prescription_medical_record_and_more'),
        ('users', '0006_alter_pharmacistprofile_license_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medication',
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_prescriptions', to='users.patientprofile'),
        ),
    ]
